#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-HiLiter
version:      0.01
version_from: HiLiter.pm
installdirs:  site
requires:
    SWISH::API:                    0.03
    HTML::HiLiter:                 0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
